### ISSUE TITLE
SAFE App Edits and Questions

### ISSUE THREAD

**Issue by KarenSAFE** [CoderTonyB/SAFEAlternatives#3]
1.Remove the word “Untitled” Location: New log Title
2.Can the name of the Log be added to the top of each log? I was in one of the logs,  I could not tell which log I was in, the Impulse control Log was easy to recognize, but not the others. 
3.Can saved logs be deleted, if so how?
4.Self Assessment: Remove email addresses from CC and BC, and remove the whole paragraph,   “Please send this e-mail to SAFE Alternatives…….. located on the “Scored Assessment” page 5th paragraph down.
5.Self Assessment: Question 44 has the following comment as an answer,            “NaN/undefined/undefined” 
6.Scrolling issues with the Impulse log, Productive Risk taking, Confrontation, and the Dilemma logs. The bottom questions get blocked by the keyboard.
7.Do you recall if there a legal disclaimer on the old app?

**Comment by CoderTonyB** [comment]
These will be added as separate questions/issues
