### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by KarenSAFE** [CoderTonyB/SAFEAlternatives#4]
Remove "NEED HELP? CLICK HERE
                800-DONTCUT (366.8288
                INFORMATION LINE"

I would like to add links to, S.A.F.E.'s website, FB page, Twitter, and Youtube channel. (and maybe later add the site you are working on for suicide) The only one that should be named is the website, FB, Twitter and Youtube can be icons.  
www.SELFINJURY.com 
Facebook:  https://www.facebook.com/SAFE-Self-Abuse-Finally-Ends-ALTERNATIVES-100545512550/
Twitter: https://twitter.com/theSAFEstore
Youtube I made animated video's explaining how to get the best out of the logs,
but I am not sure which link is the one to make public)  
https://www.youtube.com/watch?v=CchjIauNp9w&list=PL2Xom4oeN-6iP_gVabYia4ISZ1wr3m66B

https://www.youtube.com/channel/UC-dh1cEUaK6D_vK0cUVCiFQ?view_as=subscriber

**Comment by CoderTonyB** [comment]
complete

**Comment by KarenSAFE** [comment]
Fantastic!! I updated the app through iTunes, but did not see any changes, is there something on your end that you need to do, or waiting for all the edits before you put the update to be updated?
I am really thrilled with the new design, great job.
