### ISSUE TITLE
Bolder Text

### ISSUE THREAD

**Issue by KarenSAFE** [CoderTonyB/SAFEAlternatives#7]
Can you make the words located at the bottom bolder and a tad larger, and  do the same for the back arrow located top left? Many seeing impaired people have bought the previous version, and I know they will not see those words as they are now. Thanks

S.A.F.E. 
My Logs 
Self Assess

**Comment by CoderTonyB** [comment]
Can you be more specific about the words on the bottom?  Do you mean
everything in below the title bar (as in most of the app?)

**Comment by CoderTonyB** [comment]
In looking at your comment again, it looks like you mean the tab headers.

**Comment by KarenSAFE** [comment]
Yes, only the 3 words (Links) at the very bottom.

**Comment by CoderTonyB** [comment]
made bigger and bolder
